export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const UPDATE_TIME = 'UPDATE_TIME'
